# 智能问答应用配置文件
spring:
  application:
    name: ai-agent
  # 默认 dev 环境
  profiles:
    active: dev
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/CHP-AI2.0
    username: root
    password: huanghu0831
# application.yml
  ai:
    dashscope:
      api-key: 123456
      chat:
        options:
          model: qwen-plus
  # 引入独立的违禁词配置文件
  config:
    import:
      - classpath:sensitive-words.yml

server:
  port: 8080
  servlet:
    context-path: /api

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.huzi.aiagent.controller

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh-CN

# MyBatis Flex 配置（可选，大部分默认即可）
mybatis-flex:
  mapper-packages: com.huzi.chpai.mapper
  # 是否开启驼峰命名转换（默认 true）
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 逻辑删除配置（可选，后续示例会用到）
  global-config:
    logic-delete:
      column: is_deleted # 逻辑删除字段名
      value: 1 # 已删除的值
      null-value: 0 # 未删除的值



